services:
  db:
    image: postgres:latest
    container_name: express_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: express_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: express_redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:latest
    container_name: express_localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,lambda
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - CLEAR_TMP_FOLDER=0 # 🟢 Prevents the crash
    volumes:
      - localstack_data:/tmp/localstack/data

volumes:
  postgres_data:
  redis_data:
  localstack_data:
